# Generated by Django 5.1.2 on 2025-01-12 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 12, 8, 24, 18, 460662, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='Last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='Middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
