# Generated by Django 5.1.2 on 2025-01-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_account_created_at_alter_account_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Announcement', models.TextField()),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
                ('Date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
