# Generated by Django 5.1.2 on 2025-01-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
