# Generated by Django 5.1.2 on 2025-01-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_account_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Deposit_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
