# Generated by Django 5.1.2 on 2025-01-22 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_account_deposit_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Deposit_amount',
        ),
        migrations.AlterField(
            model_name='account',
            name='Current_balance',
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.account')),
            ],
        ),
    ]
