# Generated by Django 5.1.2 on 2025-01-22 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_account_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='Account_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.account'),
        ),
    ]
