# Generated by Django 5.1.2 on 2025-01-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_deposit_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Deposit_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='deposit',
        ),
    ]
