# Generated by Django 5.1.2 on 2025-01-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_remove_account_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Deposit_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='Current_balance',
            field=models.IntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='deposit',
        ),
    ]
