# Generated by Django 5.1.2 on 2025-01-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_account_deposit_amount_alter_account_current_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Withdraw_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='Current_balance',
            field=models.IntegerField(default=0.0),
        ),
    ]
