# Generated by Django 5.1.2 on 2025-01-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_account_withdraw_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Dep_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='account',
            name='With_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Current_balance',
            field=models.IntegerField(),
        ),
    ]
