# Generated by Django 5.1.2 on 2025-01-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_account_dep_date_account_with_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Transfor_amount_from',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
