# Generated by Django 5.1.2 on 2025-01-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_account_transfor_amount_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Current_balance',
            field=models.IntegerField(blank=True),
        ),
    ]
