# Generated by Django 5.1.2 on 2025-01-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_account_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Current_balance',
            field=models.IntegerField(default=0),
        ),
    ]
