# Generated by Django 5.1.2 on 2025-01-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_account_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Tran_date',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='Dep_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Deposit_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='Transfor_amount_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='With_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Withdraw_amount',
            field=models.IntegerField(default=0),
        ),
    ]
