# Generated by Django 5.1.2 on 2025-01-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_account_tran_date_alter_account_dep_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Tran_date',
        ),
    ]
