# Generated by Django 5.1.2 on 2025-01-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_alter_account_dep_date_alter_account_with_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Dep_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='With_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
