# Generated by Django 5.1.2 on 2025-01-28 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_alter_account_dep_date_alter_account_with_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Dep_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='With_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
