# Generated by Django 5.1.2 on 2025-01-28 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_alter_account_dep_date_alter_account_with_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Tran_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='Dep_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='With_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
