# Generated by Django 5.1.2 on 2025-01-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_account_tran_date_alter_account_dep_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Tran_date',
            field=models.DateField(),
        ),
    ]
