# Generated by Django 5.1.2 on 2025-01-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_alter_account_tran_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Tran_date',
        ),
    ]
