# Generated by Django 5.1.2 on 2025-01-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_remove_account_tran_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Tran_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
