# Generated by Django 5.1.2 on 2025-01-29 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_account_tran_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Tran_date',
            new_name='tran_date',
        ),
    ]
