# Generated by Django 5.1.2 on 2025-05-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_rename_tran_date_account_tran_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='tran_date',
        ),
    ]
