# Generated by Django 5.1.2 on 2026-04-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_remove_account_tran_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Tran_date',
        ),
    ]
