# Generated by Django 5.1.2 on 2026-04-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_remove_account_tran_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Dep_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='With_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
